name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 當 main 分支被推送時觸發此工作流程

jobs:
  build-deploy:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作為執行環境

    steps:
      - name: Checkout code  # 檢出代碼
        uses: actions/checkout@v3

      - name: Setup Node.js  # 設定 Node.js 環境
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 你可以根據需求更改 Node.js 版本

      - name: Install dependencies  # 安裝專案的依賴
        run: npm install

      - name: Build  # 執行 npm run build 來編譯 Vue 專案
        run: npm run build

      - name: Deploy to GitHub Pages  # 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 預設的 Token 來執行操作
          publish_dir: ./dist  # 要推送的資料夾是 dist
          publish_branch: gh-pages
          force_orphan: true

